/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Guis;

import Classes.TicTacToe;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.EOFException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.InetAddress;
import java.net.Socket;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author alingasada_sd2021
 */
public class ClientApp extends javax.swing.JFrame {

    private ObjectOutputStream output;
    private ObjectInputStream input;
    private boolean isconnected = false;
    private String chatserver;
    private Socket client;
    private TicTacToe ticTac;
    private boolean myTurn = true;

    public ClientApp() {
        initComponents();
        this.setTitle("CLIENT");
        this.setResizable(false);
        this.ticTac = new TicTacToe();
        this.chatserver = "172.16.8.11";
        this.messageField.setEditable(false);
        this.messageField.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                sendData(e.getActionCommand());
                messageField.setText("");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        panel_2 = new javax.swing.JPanel();
        but_Panel_2 = new javax.swing.JLabel();
        panel_3 = new javax.swing.JPanel();
        but_Panel_3 = new javax.swing.JLabel();
        panel_1 = new javax.swing.JPanel();
        but_Panel_1 = new javax.swing.JLabel();
        panel_9 = new javax.swing.JPanel();
        but_Panel_9 = new javax.swing.JLabel();
        panel_8 = new javax.swing.JPanel();
        but_Panel_8 = new javax.swing.JLabel();
        panel_7 = new javax.swing.JPanel();
        but_Panel_7 = new javax.swing.JLabel();
        panel_4 = new javax.swing.JPanel();
        but_Panel_4 = new javax.swing.JLabel();
        panel_5 = new javax.swing.JPanel();
        but_Panel_5 = new javax.swing.JLabel();
        panel_6 = new javax.swing.JPanel();
        but_Panel_6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        status_Label = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        messageField = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageArea = new javax.swing.JTextArea();
        game_Status = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(23, 119, 197));

        jPanel3.setBackground(new java.awt.Color(23, 119, 197));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jPanel7.setBackground(new java.awt.Color(23, 119, 197));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        panel_2.setBackground(new java.awt.Color(255, 153, 255));
        panel_2.setPreferredSize(new java.awt.Dimension(90, 90));

        but_Panel_2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        but_Panel_2.setForeground(new java.awt.Color(255, 255, 255));
        but_Panel_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        but_Panel_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                but_Panel_2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_2Layout = new javax.swing.GroupLayout(panel_2);
        panel_2.setLayout(panel_2Layout);
        panel_2Layout.setHorizontalGroup(
            panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(but_Panel_2, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        panel_2Layout.setVerticalGroup(
            panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(but_Panel_2, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        panel_3.setBackground(new java.awt.Color(255, 153, 255));
        panel_3.setPreferredSize(new java.awt.Dimension(90, 90));

        but_Panel_3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        but_Panel_3.setForeground(new java.awt.Color(255, 255, 255));
        but_Panel_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        but_Panel_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                but_Panel_3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_3Layout = new javax.swing.GroupLayout(panel_3);
        panel_3.setLayout(panel_3Layout);
        panel_3Layout.setHorizontalGroup(
            panel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(but_Panel_3, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        panel_3Layout.setVerticalGroup(
            panel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(but_Panel_3, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        panel_1.setBackground(new java.awt.Color(255, 153, 255));
        panel_1.setPreferredSize(new java.awt.Dimension(90, 90));
        panel_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_1MouseClicked(evt);
            }
        });

        but_Panel_1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        but_Panel_1.setForeground(new java.awt.Color(255, 255, 255));
        but_Panel_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        but_Panel_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                but_Panel_1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_1Layout = new javax.swing.GroupLayout(panel_1);
        panel_1.setLayout(panel_1Layout);
        panel_1Layout.setHorizontalGroup(
            panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(but_Panel_1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        panel_1Layout.setVerticalGroup(
            panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(but_Panel_1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        panel_9.setBackground(new java.awt.Color(255, 153, 255));
        panel_9.setPreferredSize(new java.awt.Dimension(90, 90));

        but_Panel_9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        but_Panel_9.setForeground(new java.awt.Color(255, 255, 255));
        but_Panel_9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        but_Panel_9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                but_Panel_9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_9Layout = new javax.swing.GroupLayout(panel_9);
        panel_9.setLayout(panel_9Layout);
        panel_9Layout.setHorizontalGroup(
            panel_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(but_Panel_9, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        panel_9Layout.setVerticalGroup(
            panel_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(but_Panel_9, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        panel_8.setBackground(new java.awt.Color(255, 153, 255));
        panel_8.setPreferredSize(new java.awt.Dimension(90, 90));

        but_Panel_8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        but_Panel_8.setForeground(new java.awt.Color(255, 255, 255));
        but_Panel_8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        but_Panel_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                but_Panel_8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_8Layout = new javax.swing.GroupLayout(panel_8);
        panel_8.setLayout(panel_8Layout);
        panel_8Layout.setHorizontalGroup(
            panel_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(but_Panel_8, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        panel_8Layout.setVerticalGroup(
            panel_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(but_Panel_8, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        panel_7.setBackground(new java.awt.Color(255, 153, 255));
        panel_7.setPreferredSize(new java.awt.Dimension(90, 90));

        but_Panel_7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        but_Panel_7.setForeground(new java.awt.Color(255, 255, 255));
        but_Panel_7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        but_Panel_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                but_Panel_7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_7Layout = new javax.swing.GroupLayout(panel_7);
        panel_7.setLayout(panel_7Layout);
        panel_7Layout.setHorizontalGroup(
            panel_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(but_Panel_7, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        panel_7Layout.setVerticalGroup(
            panel_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(but_Panel_7, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        panel_4.setBackground(new java.awt.Color(255, 153, 255));
        panel_4.setPreferredSize(new java.awt.Dimension(90, 90));

        but_Panel_4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        but_Panel_4.setForeground(new java.awt.Color(255, 255, 255));
        but_Panel_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        but_Panel_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                but_Panel_4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_4Layout = new javax.swing.GroupLayout(panel_4);
        panel_4.setLayout(panel_4Layout);
        panel_4Layout.setHorizontalGroup(
            panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(but_Panel_4, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        panel_4Layout.setVerticalGroup(
            panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(but_Panel_4, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        panel_5.setBackground(new java.awt.Color(255, 153, 255));
        panel_5.setPreferredSize(new java.awt.Dimension(90, 90));

        but_Panel_5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        but_Panel_5.setForeground(new java.awt.Color(255, 255, 255));
        but_Panel_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        but_Panel_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                but_Panel_5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_5Layout = new javax.swing.GroupLayout(panel_5);
        panel_5.setLayout(panel_5Layout);
        panel_5Layout.setHorizontalGroup(
            panel_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(but_Panel_5, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        panel_5Layout.setVerticalGroup(
            panel_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(but_Panel_5, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        panel_6.setBackground(new java.awt.Color(255, 153, 255));
        panel_6.setPreferredSize(new java.awt.Dimension(90, 90));

        but_Panel_6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        but_Panel_6.setForeground(new java.awt.Color(255, 255, 255));
        but_Panel_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        but_Panel_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                but_Panel_6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_6Layout = new javax.swing.GroupLayout(panel_6);
        panel_6.setLayout(panel_6Layout);
        panel_6Layout.setHorizontalGroup(
            panel_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(but_Panel_6, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        panel_6Layout.setVerticalGroup(
            panel_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(but_Panel_6, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(panel_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel_5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel_6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(23, 119, 197));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Status", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 3, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        status_Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        status_Label.setForeground(new java.awt.Color(255, 255, 255));
        status_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status_Label.setText("NO CONNECTION");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(status_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(status_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(23, 119, 197));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Play TicTacToe As", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 3, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(23, 119, 197));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TYPE MESSAGE HERE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 3, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        messageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messageField)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(messageField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(23, 119, 197));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MESSAGES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 3, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        messageArea.setColumns(20);
        messageArea.setRows(5);
        jScrollPane1.setViewportView(messageArea);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        game_Status.setBackground(new java.awt.Color(235, 19, 41));
        game_Status.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        game_Status.setForeground(new java.awt.Color(154, 0, 0));
        game_Status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(game_Status, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(game_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void messageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messageFieldActionPerformed

    private void panel_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_1MouseClicked

    }//GEN-LAST:event_panel_1MouseClicked

    private void but_Panel_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_Panel_1MouseClicked
        if (isconnected) {
            if (!this.but_Panel_1.getText().equals("X") && !this.but_Panel_1.getText().equals("O")) {
                this.but_Panel_1.setText("X");
                this.panel_1.setBackground(Color.black);
                sendData("1");
                ticTac.replace(1,"X");
                checkWinner(ticTac.checkWin());
            }

        }
    }//GEN-LAST:event_but_Panel_1MouseClicked

    private void but_Panel_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_Panel_2MouseClicked
        if (isconnected) {
            if (!this.but_Panel_2.getText().equals("X") && !this.but_Panel_2.getText().equals("O")) {
                this.but_Panel_2.setText("X");
                this.panel_2.setBackground(Color.black);
                sendData("2");
                ticTac.replace(2,"X");
                checkWinner(ticTac.checkWin());
            }

        }
    }//GEN-LAST:event_but_Panel_2MouseClicked

    private void but_Panel_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_Panel_3MouseClicked
        if (isconnected) {
            if (!this.but_Panel_3.getText().equals("X") && !this.but_Panel_3.getText().equals("O")) {
                this.but_Panel_3.setText("X");
                this.panel_3.setBackground(Color.black);
                sendData("3");
                ticTac.replace(3,"X");
                checkWinner(ticTac.checkWin());
            }

        }
    }//GEN-LAST:event_but_Panel_3MouseClicked

    private void but_Panel_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_Panel_4MouseClicked
        if (isconnected) {
            if (!this.but_Panel_4.getText().equals("X") && !this.but_Panel_4.getText().equals("O")) {
                this.but_Panel_4.setText("X");
                this.panel_4.setBackground(Color.black);
                sendData("4");
                ticTac.replace(4,"X");
                checkWinner(ticTac.checkWin());
            }

        }
    }//GEN-LAST:event_but_Panel_4MouseClicked

    private void but_Panel_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_Panel_5MouseClicked
        if (isconnected) {
            if (!this.but_Panel_5.getText().equals("X") && !this.but_Panel_5.getText().equals("O")) {
                this.but_Panel_5.setText("X");
                this.panel_5.setBackground(Color.black);
                sendData("5");
                ticTac.replace(5,"X");
                checkWinner(ticTac.checkWin());
            }

        }
    }//GEN-LAST:event_but_Panel_5MouseClicked

    private void but_Panel_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_Panel_6MouseClicked
        if (isconnected) {
            if (!this.but_Panel_6.getText().equals("X") && !this.but_Panel_6.getText().equals("O")) {
                this.but_Panel_6.setText("X");
                this.panel_6.setBackground(Color.black);
                sendData("6");
                ticTac.replace(6,"X");
                checkWinner(ticTac.checkWin());
            }

        }
    }//GEN-LAST:event_but_Panel_6MouseClicked

    private void but_Panel_7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_Panel_7MouseClicked
        if (isconnected) {
            if (!this.but_Panel_7.getText().equals("X") && !this.but_Panel_7.getText().equals("O")) {
                this.but_Panel_7.setText("X");
                this.panel_7.setBackground(Color.black);
                sendData("7");
                ticTac.replace(7,"X");
                checkWinner(ticTac.checkWin());
            }

        }
    }//GEN-LAST:event_but_Panel_7MouseClicked

    private void but_Panel_8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_Panel_8MouseClicked
        if (isconnected) {
            if (!this.but_Panel_8.getText().equals("X") && !this.but_Panel_8.getText().equals("O")) {
                this.but_Panel_8.setText("X");
                this.panel_8.setBackground(Color.black);
                sendData("8");
                ticTac.replace(8,"X");
                checkWinner(ticTac.checkWin());
            }

        }
    }//GEN-LAST:event_but_Panel_8MouseClicked

    private void but_Panel_9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_Panel_9MouseClicked
        if (isconnected) {
            if (!this.but_Panel_9.getText().equals("X") && !this.but_Panel_9.getText().equals("O")) {
                this.but_Panel_9.setText("X");
                this.panel_9.setBackground(Color.black);
                sendData("9");
                ticTac.replace(9,"X");
                checkWinner(ticTac.checkWin());
            }

        }
    }//GEN-LAST:event_but_Panel_9MouseClicked

    public void runClient() {
        try // connect to server, get streams, process connection
        {
            connectToServer(); // create a Socket to make connection
            getStreams(); // get the input and output streams
            processConnection(); // process connection
        } // end try
        catch (EOFException eofException) {
            displayMessage("\nClient terminated connection");
        } // end catch
        catch (IOException ioException) {
            ioException.printStackTrace();
        } // end catch
        finally {
            closeConnection();
        }
    }

    private void connectToServer() throws IOException {
        this.status_Label.setText("Attempting connection....");
        client = new Socket(InetAddress.getByName(chatserver), 2020);
        this.status_Label.setText("Connected to: " + client.getInetAddress().getHostName());
        isconnected = true;
        displayMessage("Connected to: " + client.getInetAddress().getHostName());
    }

    private void getStreams() throws IOException {
        output = new ObjectOutputStream(client.getOutputStream());
        output.flush();

        input = new ObjectInputStream(client.getInputStream());
        displayMessage("\nGot I/O streams\n");
    }

    private void processConnection() throws IOException {
        String message = "Connection Successful";
        sendData(message);
        setTextFieldEditable(true);

        do {
            try {
                message = (String) input.readObject();
                displayMessage("\n" + message);
                filterInput("" + message.charAt(message.length() - 1));
            } catch (ClassNotFoundException classNotFoundException) {
                displayMessage("\nUnknown object type received");
            }

        } while (!message.equals("SERVER>>> TERMINATE"));
    }

    private void closeConnection() {
        displayMessage("\nTerminating Connection\n");
        setTextFieldEditable(false);
        try {
            output.close();
            input.close();
            client.close();
            isconnected = false;
        } catch (IOException ioe) {
            ioe.printStackTrace();
        }
    }

    private void sendData(String message) {
        try {
            output.writeObject("CLIENT>>> " + message);
            output.flush();
            displayMessage("\nCLIENT>>> " + message);
        } catch (IOException ioe) {
            this.messageArea.append("\n Error writing object");
        }
    }

    private void displayMessage(final String message) {
        this.messageArea.append(message);
    }

    private void setTextFieldEditable(boolean b) {
        this.messageField.setEditable(b);
    }

    private void filterInput(String Number) {
        switch (Number) {
            case "1":
                changeProperty(this.but_Panel_1, this.panel_1);
                ticTac.replace(Integer.parseInt(Number),"O");
                checkWinner(ticTac.checkWin());
                break;
            case "2":
                changeProperty(this.but_Panel_2, this.panel_2);
                 ticTac.replace(Integer.parseInt(Number),"O");
                 checkWinner(ticTac.checkWin());
                break;
            case "3":
                changeProperty(this.but_Panel_3, this.panel_3);
                 ticTac.replace(Integer.parseInt(Number),"O");
                checkWinner(ticTac.checkWin());
                break;
            case "4":
                changeProperty(this.but_Panel_4, this.panel_4);
                ticTac.replace(Integer.parseInt(Number),"O");
                checkWinner(ticTac.checkWin());
                break;
            case "5":
                changeProperty(this.but_Panel_5, this.panel_5);
                ticTac.replace(Integer.parseInt(Number),"O");
                checkWinner(ticTac.checkWin());
                break;
            case "6":
                changeProperty(this.but_Panel_6, this.panel_6);
                ticTac.replace(Integer.parseInt(Number),"O");
                checkWinner(ticTac.checkWin());
                break;
            case "7":
                changeProperty(this.but_Panel_7, this.panel_7);
                ticTac.replace(Integer.parseInt(Number),"O");
                checkWinner(ticTac.checkWin());
                break;
            case "8":
                changeProperty(this.but_Panel_8, this.panel_8);
                ticTac.replace(Integer.parseInt(Number),"O");
                checkWinner(ticTac.checkWin());
                break;
            case "9":
                changeProperty(this.but_Panel_9, this.panel_9);
                ticTac.replace(Integer.parseInt(Number),"O");
                checkWinner(ticTac.checkWin());
                break;
            default:
                break;
        }
    }

    private void changeProperty(JLabel but_Panel_Num, JPanel panel_Num) {
        but_Panel_Num.setText("O");
        panel_Num.setBackground(Color.black);
    }
    
    private void checkWinner(Object[]checkWin) {
        if((boolean)checkWin[0]){
            switch((String)checkWin[1]){
                case "X":this.game_Status.setText("You WIN!");this.game_Status.setForeground(Color.green);break;
                case "O":this.game_Status.setText("You LOSE! Server WIN!");this.game_Status.setForeground(Color.red);break;
                default:break;
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel but_Panel_1;
    private javax.swing.JLabel but_Panel_2;
    private javax.swing.JLabel but_Panel_3;
    private javax.swing.JLabel but_Panel_4;
    private javax.swing.JLabel but_Panel_5;
    private javax.swing.JLabel but_Panel_6;
    private javax.swing.JLabel but_Panel_7;
    private javax.swing.JLabel but_Panel_8;
    private javax.swing.JLabel but_Panel_9;
    private javax.swing.JLabel game_Status;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea messageArea;
    private javax.swing.JTextField messageField;
    private javax.swing.JPanel panel_1;
    private javax.swing.JPanel panel_2;
    private javax.swing.JPanel panel_3;
    private javax.swing.JPanel panel_4;
    private javax.swing.JPanel panel_5;
    private javax.swing.JPanel panel_6;
    private javax.swing.JPanel panel_7;
    private javax.swing.JPanel panel_8;
    private javax.swing.JPanel panel_9;
    private javax.swing.JLabel status_Label;
    // End of variables declaration//GEN-END:variables

    

}
